import math

print(math.ceil(2.9))
x = 2.9
print(abs(-2.9))
print(math.floor(x))
print(math.factorial(5))
print(math.sqrt(25))
print(math.pow(2, 3))
print(math.pi)
print(math.e)
print(math.sin(90))
print(math.cos(90))
print(math.tan(90))
print(math.degrees(90))
print(math.radians(90))
print(math.log(10))
print(math.log10(100))
print(math.log2(8))
print(math.log1p(1))
print(math.exp(1))
print(math.acos(1))
print(math.asin(1))
print(math.atan(1))
print(math.atan2(1, 1))
print(math.hypot(3, 4))
print(math.isclose(1.0, 1.0))
print(math.isfinite(1.0))
print(math.isinf(1.0))
print(math.isnan(1.0))
print(math.isqrt(25))
print(math.dist((0, 0), (3, 4)))
print(math.prod([1, 2, 3, 4, 5]))
print(math.perm(5, 2))
print(math.comb(5, 2))
print(math.gcd(12, 15))
print(math.lcm(12, 15))
print(math.degrees(1))
print(math.radians(180))
print(math.trunc(2.9))
print(math.remainder(10, 3))
print(math.copysign(1, -1))
print(math.ulp(1.0))
print(math.nextafter(1.0, 2.0))
print(math.ulp(1.0))






